### PR TITLE
small changes to fib, added rust-cookbook link

### PR DESCRIPTION
**Pull request by leshow**
I made the fibonacci functions take a u64 instead of a usize, the usize type AFAIK is mainly for indexing pointers, everything else should be u32/u64/i32/i64 for integers (https://stackoverflow.com/questions/29592256/whats-the-difference-between-usize-and-u32). 

I removed the type postfix and the explicit return, this introduces the value of inference and is more idiomatic 'rusty' code.

Added a dynamic programming fib for comparison, it includes a for .. in loop which I think is a nice thing to learn early on.

Also, there is a similar project going on at rust-cookbook (linked in the readme), I highly recommend you check it out! Lots of great stuff there. Perhaps you can find something to contribute there unless your goals here are orthogonal.

Cheers!

### CODE REVIEW

**Comment by snowzurfer** [comment]
Thanks for your contribution! I have had a look at the stackoverflow post you linked, and to me it seems like instead it is a good idea to use `usize` rather than `u64`; on a 32-bit machine that would be slower, whereas using `usize` would guarantee that we get the right amount of bytes.
From the same stackoverflow:

> As the documentation states usize is pointer-sized, thus its actual size depends on the architecture your are compiling your program for.    
As an example, on a 32 bit x86 computer, usize = u32, while on x86_64 computers, usize = u64.    
usize gives you the guarantee to be always big enough to hold any pointer or any offset in a data structure, while u32 can be too small on some architectures.

I will keep most of your changes but change back to using `usize`

**Comment by leshow** [comment]
According to the Rust book, you should generally not be using usize/isize for your regular integer operations, it's meant for indexing. Perhaps I was wrong to use i64 in the example though, and i32 would have been better:

> "So how do you know which type of integer to use? If you’re unsure, Rust’s defaults are generally  good choices, and integer types default to i32: it’s generally the fastest, even on 64-bit systems. The  primary situation in which you’d use isize or usize is when indexing some sort of collection."

https://doc.rust-lang.org/stable/book/second-edition/ch03-02-data-types.html#integer-types

**Comment by leshow** [comment]
And indeed, even in the quote that you pasted, it says 
> gives you the guarantee to be always big enough to hold any **pointer or any offset** in a data structure, while u32 can be too small on some architectures.

I made this mistake also when I started using Rust, back then the variable sized integer types were actually called `int`/`uint` if memory serves, which made it even more confusing. I think a large reason for the change to `usize`/`isize` was to distance the naming from `int` and discourage use as your standard integer type. Don't quote me on that last bit though 👅 

Edit: Ah, here we go, I found the old RFC: https://github.com/rust-lang/rust-guidelines/issues/24

**Comment by snowzurfer** [comment]
But why would I not want to use `usize`/`isize` if that gives me the guarantee that it will hold the largest number of bytes depending on my architecture? If I use `u32`/`i32` then I cannot take advantage of using larger numbers on 64-bit architectures.

To me the quote
> gives you the guarantee to be always big enough to hold any pointer or any offset in a data structure, while u32 can be too small on some architectures.

tells me that I should use `usize` in this case, because, from the same Stackoverflow answer:
> As an example, on a 32 bit x86 computer, usize = u32, while on x86_64 computers, usize = u64.

**Comment by leshow** [comment]
If you read the RFC I linked, they mention i32 being faster. More details are in the RFC, along with all the arguments against using usize/isize as a default integer type.

 https://github.com/rust-lang/rfcs/pull/161/files?short_path=e5dd6d3#integer-type-style-guidelines
(When they refer to uint/int they are talking about today's usize/isize)

The SO post is just saying how usize/isize changes to be the correct size for indexing depending on architecture, making it the right type for indexing and offsets, it's not saying to use it as your default integer type. The fib code isn't doing any indexing or offset, it's calculating some number result, so it should be i32.

The official book recommends i32, as does the RFC, if this repo is meant to be intro material for beginners it should be in line with the other resources. Anyway it's your repo of course, completely up to you if you don't want to follow the guideline.

**Pull request merged**
